/**
 * Star-naming helpers.
 *
 * Each star in a galaxy gets a single-word sci-fi display name
 * (e.g. "Vulcan", "Phyco", "Klystron", "Proxima", "Sirius"). Names
 * are unique within the galaxy.
 *
 * `STAR_NAMES` is the source of truth for the actual word list;
 * a curated pool of ~600 short sci-fi-sounding words (real stars,
 * mythology, engineering terms, and patterned syllables). Pool is
 * large enough that the disambiguator fallback (numeric suffix)
 * never fires for any in-game galaxy size.
 *
 * Mirrored as placeholders in `quint/galaxy.qnt` — the spec names
 * the scheme; this file is the source of truth for the words.
 *
 * Determinism: pass the same `rng` as the rest of galaxy generation
 * to get reproducible names for a given seed.
 */

export const STAR_NAMES: ReadonlyArray<string> = [
  'Alderan',
  'Altair',
  'Andromeda',
  'Antares',
  'Arcturus',
  'Bellatrix',
  'Betelgeuse',
  'Capella',
  'Castor',
  'Cygnus',
  'Deneb',
  'Eridanus',
  'Fomalhaut',
  'Helios',
  'Hydra',
  'Lyra',
  'Mira',
  'Mizar',
  'Orion',
  'Perseus',
  'Phoenix',
  'Pollux',
  'Polaris',
  'Proxima',
  'Regulus',
  'Rigel',
  'Sirius',
  'Taurus',
  'Vega',
  'Vulcan',
  'Centauri',
  'Draco',
  'Epsilon',
  'Kronos',
  'Pleiad',
  'Sagittar',
  'Pegasus',
  'Lyrae',
  'Aquila',
  'Borealis',
  'Australis',
  'Canopus',
  'Aldebaran',
  'Achernar',
  'Acrux',
  'Algol',
  'Alnilam',
  'Alphard',
  'Atria',
  'Avior',
  'Diphda',
  'Elnath',
  'Enif',
  'Gacrux',
  'Ginan',
  'Hadar',
  'Hamal',
  'Kaus',
  'Mimosa',
  'Mintaka',
  'Athena',
  'Apollo',
  'Ares',
  'Artemis',
  'Atlas',
  'Cerberus',
  'Chaos',
  'Cronus',
  'Demeter',
  'Dionysus',
  'Echo',
  'Gaia',
  'Hades',
  'Hera',
  'Hermes',
  'Hyperion',
  'Iris',
  'Janus',
  'Medusa',
  'Minerva',
  'Nemesis',
  'Nereus',
  'Odysseus',
  'Olympus',
  'Orpheus',
  'Perses',
  'Phaeton',
  'Poseidon',
  'Prometheus',
  'Rhea',
  'Selene',
  'Styx',
  'Tartarus',
  'Themis',
  'Theseus',
  'Triton',
  'Typhon',
  'Vesta',
  'Zeus',
  'Charon',
  'Styxan',
  'Penumbra',
  'Aether',
  'Erebus',
  'Moros',
  'Pontus',
  'Thanatos',
  'Quantum',
  'Plasma',
  'Photon',
  'Neutron',
  'Proton',
  'Boson',
  'Gluon',
  'Fermion',
  'Hadron',
  'Meson',
  'Lepton',
  'Quark',
  'Tachyon',
  'Wormhole',
  'Singular',
  'Lumen',
  'Phaser',
  'Phyco',
  'Klystron',
  'Warpzon',
  'Transmut',
  'Dissipat',
  'Resonant',
  'Cumulus',
  'Stratus',
  'Cirrus',
  'Nimbus',
  'Coronal',
  'Magnetar',
  'Pulsar',
  'Quasar',
  'Celesti',
  'Astromet',
  'Photonic',
  'Cryogen',
  'Voltaic',
  'Galvanik',
  'Turbinic',
  'Cryovol',
  'Cryolith',
  'Hydriac',
  'Venturis',
  'Vortexia',
  'Ergosphe',
  'Plasmoid',
  'Asterion',
  'Heliacal',
  'Syzygia',
  'Zenitha',
  'Nadiria',
  'Tyrium',
  'Fyren',
  'Tovan',
  'Umbion',
  'Thayne',
  'Ethoma',
  'Galean',
  'Rheium',
  'Ilyne',
  'Lyrius',
  'Faeyth',
  'Vexan',
  'Xanium',
  'Vexeth',
  'Faeium',
  'Valius',
  'Dorion',
  'Ushium',
  'Weyeth',
  'Caeen',
  'Othax',
  'Jakaid',
  'Ilyth',
  'Morir',
  'Fenax',
  'Osbaea',
  'Ioreus',
  'Fenyth',
  'Ithean',
  'Nyxoma',
  'Balaid',
  'Galaid',
  'Voron',
  'Gloan',
  'Rhioid',
  'Saeoid',
  'Fyrion',
  'Lhoyne',
  'Gloix',
  'Runax',
  'Lyroid',
  'Acraid',
  'Weyyne',
  'Arean',
  'Lyrium',
  'Phoan',
  'Thaon',
  'Naxus',
  'Ilaea',
  'Balos',
  'Yorara',
  'Lyraid',
  'Vorax',
  'Etheia',
  'Wraix',
  'Hyrene',
  'Cyroma',
  'Valar',
  'Faeax',
  'Rheian',
  'Hekius',
  'Nyxene',
  'Umbius',
  'Munada',
  'Pavaid',
  'Kalyne',
  'Loxium',
  'Xenax',
  'Caeoid',
  'Kryion',
  'Runoid',
  'Galon',
  'Zenaid',
  'Cyroid',
  'Tyrax',
  'Yggir',
  'Ethyn',
  'Morios',
  'Rheora',
  'Saeada',
  'Zepoia',
  'Tovoia',
  'Kyryn',
  'Kryaea',
  'Kaloma',
  'Elyius',
  'Pavion',
  'Phoax',
  'Pyrene',
  'Yoran',
  'Nyxos',
  'Moroia',
  'Yorion',
  'Kyron',
  'Nerir',
  'Munix',
  'Ashora',
  'Naxos',
  'Zepix',
  'Runus',
  'Ethaid',
  'Quous',
  'Wraoma',
  'Galan',
  'Vexon',
  'Valon',
  'Tyrean',
  'Caeix',
  'Styium',
  'Faean',
  'Nerar',
  'Beloma',
  'Yggoid',
  'Lyroia',
  'Yoryn',
  'Ioroia',
  'Phoon',
  'Jakoma',
  'Vexora',
  'Ashion',
  'Wynos',
  'Thaeia',
  'Galyne',
  'Phoeus',
  'Belar',
  'Hekios',
  'Pavax',
  'Zenon',
  'Acrax',
  'Quoian',
  'Weyoid',
  'Lyrix',
  'Hyroid',
  'Galada',
  'Zepian',
  'Jovos',
  'Rhiara',
  'Ethyth',
  'Cyrus',
  'Styen',
  'Ashyn',
  'Ilian',
  'Usheus',
  'Hekyn',
  'Xenion',
  'Zepyn',
  'Ushius',
  'Jakon',
  'Runyn',
  'Hekax',
  'Wynean',
  'Quoir',
  'Loxen',
  'Thaian',
  'Ithian',
  'Zenax',
  'Ebrar',
  'Jovion',
  'Xanian',
  'Fenan',
  'Jakix',
  'Rhion',
  'Lhoeth',
  'Arir',
  'Jakian',
  'Hyryne',
  'Hekir',
  'Rheion',
  'Yggaea',
  'Hyrean',
  'Kryan',
  'Wraora',
  'Fyrios',
  'Jovaid',
  'Zenius',
  'Ithios',
  'Pavoid',
  'Acrara',
  'Ioraea',
  'Dryara',
  'Kyros',
  'Balir',
  'Lyrus',
  'Neren',
  'Yggoia',
  'Balyne',
  'Valoid',
  'Xenene',
  'Wraus',
  'Kryos',
  'Loxyn',
  'Jovora',
  'Rhiix',
  'Kalen',
  'Faeara',
  'Osbyn',
  'Galaea',
  'Fenene',
  'Rheeth',
  'Runix',
  'Ilus',
  'Naxean',
  'Gloium',
  'Faeen',
  'Yggeus',
  'Voros',
  'Belyne',
  'Seloma',
  'Umbax',
  'Kyrene',
  'Brion',
  'Phoos',
  'Ethix',
  'Zenion',
  'Loxix',
  'Rhiius',
  'Hekus',
  'Saeyn',
  'Drair',
  'Selara',
  'Quoaid',
  'Kryyth',
  'Ethir',
  'Saeax',
  'Munax',
  'Ilion',
  'Toven',
  'Ioren',
  'Elyora',
  'Kalion',
  'Morora',
  'Iorar',
  'Pyraid',
  'Rhian',
  'Xanius',
  'Kaleia',
  'Iloid',
  'Xenir',
  'Xanios',
  'Othada',
  'Vexium',
  'Kyrax',
  'Ethoia',
  'Arix',
  'Jovaea',
  'Caeean',
  'Dryeus',
  'Xanan',
  'Galora',
  'Hekos',
  'Acraea',
  'Gloen',
  'Hyraea',
  'Nyxean',
  'Ushen',
  'Cyrax',
  'Jovir',
  'Selan',
  'Yggium',
  'Fenos',
  'Ebrir',
  'Nerara',
  'Valir',
  'Ethium',
  'Jovyth',
  'Voryth',
  'Morax',
  'Wraan',
  'Elyix',
  'Kryon',
  'Osbon',
  'Ethian',
  'Doroma',
  'Jovene',
  'Cyrene',
  'Ileus',
  'Rhiion',
  'Xenyne',
  'Rhiora',
  'Yorax',
  'Lyryth',
  'Xenan',
  'Yggean',
  'Valix',
  'Osbora',
  'Paven',
  'Loxeth',
  'Vexaid',
  'Tovos',
  'Vexeia',
  'Myrios',
  'Acrix',
  'Phoar',
  'Zenyne',
  'Fyreia',
  'Acrus',
  'Fenoid',
  'Caeaea',
  'Corara',
  'Pavium',
  'Cyrian',
  'Briean',
  'Baloid',
  'Phoyne',
  'Yorian',
  'Pyrian',
  'Quoium',
  'Ebryth',
  'Weyos',
  'Tyreus',
  'Cyryn',
  'Loxeia',
  'Loxoid',
  'Rhiian',
  'Runium',
  'Lhous',
  'Kyrus',
  'Tovios',
  'Thaoid',
  'Loxios',
  'Hyrus',
  'Styan',
  'Voraea',
  'Ebran',
  'Hekium',
  'Kalix',
  'Iorara',
  'Cyrium',
  'Moryne',
  'Quoon',
  'Draene',
  'Gloios',
  'Umban',
  'Draada',
  'Tyraea',
  'Munan',
  'Dryeia',
  'Zeneus',
  'Xanaid',
  'Vexir',
  'Gaeius',
  'Vexos',
  'Elyios',
  'Tyrix',
  'Thaos',
  'Caeeia',
  'Loxar',
  'Fyryne',
  'Pavyn',
  'Kalean',
  'Wynius',
  'Corix',
  'Belios',
  'Loxos',
  'Tyrar',
  'Lyraea',
  'Pyrius',
  'Gaeon',
  'Rheir',
  'Acreia',
  'Tovora',
  'Pyren',
  'Rhiean',
  'Baleia',
  'Wynora',
  'Wynix',
  'Yorar',
  'Balian',
  'Arora',
  'Phoium',
  'Yoraid',
  'Elyir',
  'Moryth',
  'Myrus',
  'Aran',
  'Seloid',
  'Xenian',
  'Acrion',
  'Wynyth',
  'Vexen',
  'Cyrada',
  'Zenoia',
  'Galeus',
  'Fenius',
  'Gloeus',
  'Selir',
  'Rheios',
  'Dryaid',
  'Draon',
  'Zepean',
  'Fyros',
  'Draara',
  'Jakium',
  'Ilaid',
  'Caeus',
  'Corora',
  'Thaax',
  'Otheia',
  'Gaeaid',
  'Ithora',
  'Ilada',
  'Xanoma',
  'Kyrius',
  'Briyne',
  'Quooid',
  'Naxyne',
  'Nyxir',
  'Iorian',
  'Itheus',
  'Loxax',
  'Naxax',
  'Morion',
  'Neraea',
  'Thaora',
  'Ioroid',
  'Runius',
  'Valion',
  'Ioreia',
  'Pavian',
  'Naxion',
  'Tovir',
  'Beloid',
  'Ebrix',
  'Pyreus',
  'Myrium',
  'Saeus',
  'Rheaid',
  'Otheus',
  'Dryion',
  'Fyroma',
  'Saeene',
  'Lhoyn',
  'Zeneth',
  'Osbium',
  'Balara',
  'Caeoia',
  'Runene',
  'Yggada',
  'Ithada',
  'Loxoia',
  'Wynene',
  'Styeia',
  'Rhius'
];

/**
 * Minimal structural contract a star must satisfy to be nameable.
 * Useful for tests that hand-build star fixtures without depending
 * on the full `Star` type.
 */
export interface NameableStar {
  readonly id: number;
}

export interface NamedStar extends NameableStar {
  readonly name: string;
}

export function nameStars<StarT extends NameableStar>(
  stars: ReadonlyArray<StarT>,
  rng: () => number,
): Array<StarT & NamedStar> {
  const used = new Set<string>();
  const out: Array<StarT & NamedStar> = [];

  // Single-word names: copy the pool and shuffle it. Pool size
  // (~600) is far larger than the maximum in-game galaxy size
  // (Huge = 72 stars), so the disambiguator fallback is here only
  // as a safety net; in practice every star will get a clean name
  // from the shuffled pool on the first walk.
  const pool = shuffleStable(STAR_NAMES, rng);

  for (const star of stars) {
    let chosen: string | null = null;

    // Start each star at a different offset into the shuffled pool
    // so neighbouring stars don't pull consecutive names from the
    // same corner of the shuffle. Wrap around twice to cover the
    // (in practice unreachable) exhaustion case.
    const offset = Math.floor(rng() * pool.length);
    for (let step = 0; step < pool.length * 2; step++) {
      const candidate = pool[(offset + step) % pool.length]!;
      if (!used.has(candidate)) {
        chosen = candidate;
        break;
      }
    }

    if (chosen === null) {
      // Collision storm (pool exhausted) — append a numeric
      // disambiguator. Picks a name from the pool and appends "<n>"
      // until unique. Bumping n starts at 2 so the first generated
      // name is identical to the picked pool entry.
      let n = 2;
      const seedPool = shuffleStable(STAR_NAMES, rng);
      while (true) {
        const seed = seedPool[n % seedPool.length]!;
        const candidate = `${seed}${n}`;
        if (!used.has(candidate)) {
          chosen = candidate;
          break;
        }
        n++;
      }
    }

    used.add(chosen);
    out.push({ ...star, name: chosen });
  }

  return out;
}

/**
 * Fisher-Yates shuffle returning a *new* array.
 */
function shuffleStable<T>(arr: ReadonlyArray<T>, rng: () => number): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = a[i]!;
    a[i] = a[j]!;
    a[j] = tmp;
  }
  return a;
}

